package com.droidnova.fliptomute.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// The themes that are earned (future features F21, F36): Forest, Rose and Midnight. They are Flip to
// Mute's own, built on the same roles as the three schemes copied from Secret Calculator in Color.kt.
// Midnight is true black in dark mode and a neutral graphite in light mode.

internal val ForestColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFF9CD67D),
    onPrimary = Color(0xFF0D3900),
    primaryContainer = Color(0xFF205107),
    onPrimaryContainer = Color(0xFFB7F397),
    secondary = Color(0xFFBDCBB0),
    onSecondary = Color(0xFF283421),
    secondaryContainer = Color(0xFF3E4A36),
    onSecondaryContainer = Color(0xFFD9E7CB),
    tertiary = Color(0xFFA0CFD0),
    onTertiary = Color(0xFF003738),
    tertiaryContainer = Color(0xFF1E4E4F),
    onTertiaryContainer = Color(0xFFBCEBEC),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF11140F),
    onBackground = Color(0xFFE1E4DA),
    surface = Color(0xFF11140F),
    onSurface = Color(0xFFE1E4DA),
    surfaceVariant = Color(0xFF43483E),
    onSurfaceVariant = Color(0xFFC3C8BB),
    outline = Color(0xFF8D9286),
    outlineVariant = Color(0xFF43483E),
    inverseSurface = Color(0xFFE1E4DA),
    inverseOnSurface = Color(0xFF2E312B),
    inversePrimary = Color(0xFF386A20),
    surfaceContainer = Color(0xFF1D211B),
    surfaceContainerHigh = Color(0xFF272B25),
)

internal val ForestLightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF386A20),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB7F397),
    onPrimaryContainer = Color(0xFF042100),
    secondary = Color(0xFF55624C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD9E7CB),
    onSecondaryContainer = Color(0xFF131F0D),
    tertiary = Color(0xFF386667),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCEBEC),
    onTertiaryContainer = Color(0xFF002021),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF8FAF0),
    onBackground = Color(0xFF191D16),
    surface = Color(0xFFF8FAF0),
    onSurface = Color(0xFF191D16),
    surfaceVariant = Color(0xFFDFE4D7),
    onSurfaceVariant = Color(0xFF43483E),
    outline = Color(0xFF73796E),
    outlineVariant = Color(0xFFC3C8BB),
    inverseSurface = Color(0xFF2E312B),
    inverseOnSurface = Color(0xFFEFF2E8),
    inversePrimary = Color(0xFF9CD67D),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F5EA),
    surfaceContainer = Color(0xFFECEFE4),
    surfaceContainerHigh = Color(0xFFE6E9DF),
    surfaceContainerHighest = Color(0xFFE1E4DA),
)

internal val RoseColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB1C8),
    onPrimary = Color(0xFF5E1133),
    primaryContainer = Color(0xFF7B2949),
    onPrimaryContainer = Color(0xFFFFD9E2),
    secondary = Color(0xFFE3BDC6),
    onSecondary = Color(0xFF422931),
    secondaryContainer = Color(0xFF5A3F47),
    onSecondaryContainer = Color(0xFFFFD9E2),
    tertiary = Color(0xFFEFBD94),
    onTertiary = Color(0xFF48290B),
    tertiaryContainer = Color(0xFF623F20),
    onTertiaryContainer = Color(0xFFFFDCC1),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF191113),
    onBackground = Color(0xFFEFDFE1),
    surface = Color(0xFF191113),
    onSurface = Color(0xFFEFDFE1),
    surfaceVariant = Color(0xFF514347),
    onSurfaceVariant = Color(0xFFD5C2C6),
    outline = Color(0xFF9E8C90),
    outlineVariant = Color(0xFF514347),
    inverseSurface = Color(0xFFEFDFE1),
    inverseOnSurface = Color(0xFF372E30),
    inversePrimary = Color(0xFF984061),
    surfaceContainer = Color(0xFF261D1F),
    surfaceContainerHigh = Color(0xFF31282A),
)

internal val RoseLightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF984061),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E2),
    onPrimaryContainer = Color(0xFF3E001D),
    secondary = Color(0xFF74565F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E2),
    onSecondaryContainer = Color(0xFF2B151C),
    tertiary = Color(0xFF7C5635),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCC1),
    onTertiaryContainer = Color(0xFF2E1500),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF22191C),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF22191C),
    surfaceVariant = Color(0xFFF2DDE1),
    onSurfaceVariant = Color(0xFF514347),
    outline = Color(0xFF837377),
    outlineVariant = Color(0xFFD5C2C6),
    inverseSurface = Color(0xFF372E30),
    inverseOnSurface = Color(0xFFFDEDEF),
    inversePrimary = Color(0xFFFFB1C8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF0F2),
    surfaceContainer = Color(0xFFFAEAEC),
    surfaceContainerHigh = Color(0xFFF4E4E6),
    surfaceContainerHighest = Color(0xFFEFDFE1),
)

internal val MidnightColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFE2E2E2),
    onPrimary = Color(0xFF1B1B1B),
    primaryContainer = Color(0xFF3A3A3A),
    onPrimaryContainer = Color(0xFFE2E2E2),
    secondary = Color(0xFFC6C6C6),
    onSecondary = Color(0xFF303030),
    secondaryContainer = Color(0xFF474747),
    onSecondaryContainer = Color(0xFFE2E2E2),
    tertiary = Color(0xFFB9C8DA),
    onTertiary = Color(0xFF23323F),
    tertiaryContainer = Color(0xFF3A4857),
    onTertiaryContainer = Color(0xFFD5E4F7),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    // True black: on OLED screens these pixels are off
    background = Color(0xFF000000),
    onBackground = Color(0xFFE2E2E2),
    surface = Color(0xFF000000),
    onSurface = Color(0xFFE2E2E2),
    surfaceVariant = Color(0xFF3B3B3B),
    onSurfaceVariant = Color(0xFFC6C6C6),
    outline = Color(0xFF919191),
    outlineVariant = Color(0xFF3B3B3B),
    inverseSurface = Color(0xFFE2E2E2),
    inverseOnSurface = Color(0xFF303030),
    inversePrimary = Color(0xFF5E5E5E),
    surfaceContainer = Color(0xFF121212),
    surfaceContainerHigh = Color(0xFF1C1C1C),
)

internal val MidnightLightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF3B3B3F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE2E2E6),
    onPrimaryContainer = Color(0xFF1B1B1F),
    secondary = Color(0xFF5E5E62),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE3E2E6),
    onSecondaryContainer = Color(0xFF1B1B1F),
    tertiary = Color(0xFF526070),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD5E4F7),
    onTertiaryContainer = Color(0xFF0E1D2A),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFAF9FB),
    onBackground = Color(0xFF1B1B1D),
    surface = Color(0xFFFAF9FB),
    onSurface = Color(0xFF1B1B1D),
    surfaceVariant = Color(0xFFE3E2E6),
    onSurfaceVariant = Color(0xFF46464A),
    outline = Color(0xFF77777A),
    outlineVariant = Color(0xFFC7C6CA),
    inverseSurface = Color(0xFF303032),
    inverseOnSurface = Color(0xFFF2F0F2),
    inversePrimary = Color(0xFFC7C6CA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F3F5),
    surfaceContainer = Color(0xFFEEEDEF),
    surfaceContainerHigh = Color(0xFFE9E8EA),
    surfaceContainerHighest = Color(0xFFE3E2E4),
)
